version: "3.1"

services:
  rng:
    image: bataylor976/dockercoins_rng:1.0
    networks:
    - dockercoins
    ports:
    - "8001:80"
    deploy:
      mode: global

  hasher:
    image: bataylor976/dockercoins_hasher:1.0
    networks:
    - dockercoins
    ports:
    - "8002:80"

  webui:
    image: bataylor976/dockercoins_webui:1.0
    networks:
    - dockercoins
    ports:
    - "80:80"

  redis:
    image: redis
    networks:
    - dockercoins

  worker:
    image: bataylor976/dockercoins_worker:1.0
    networks:
    - dockercoins
    deploy:
       replicas: 10

networks:
    dockercoins:
